// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/pennev1/penne.proto

package pennev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PenneService_CheckHealth_FullMethodName           = "/penne.v1.PenneService/CheckHealth"
	PenneService_GetUser_FullMethodName               = "/penne.v1.PenneService/GetUser"
	PenneService_CreateTransaction_FullMethodName     = "/penne.v1.PenneService/CreateTransaction"
	PenneService_GetTransaction_FullMethodName        = "/penne.v1.PenneService/GetTransaction"
	PenneService_GetTransactionsByUser_FullMethodName = "/penne.v1.PenneService/GetTransactionsByUser"
	PenneService_UpdateTransaction_FullMethodName     = "/penne.v1.PenneService/UpdateTransaction"
	PenneService_DeleteTransaction_FullMethodName     = "/penne.v1.PenneService/DeleteTransaction"
	PenneService_GetEnvelope_FullMethodName           = "/penne.v1.PenneService/GetEnvelope"
	PenneService_GetEnvelopesByUser_FullMethodName    = "/penne.v1.PenneService/GetEnvelopesByUser"
)

// PenneServiceClient is the client API for PenneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type PenneServiceClient interface {
	CheckHealth(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// User
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// Transaction
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*TransactionItem, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*TransactionItem, error)
	GetTransactionsByUser(ctx context.Context, in *GetTransactionsByUserRequest, opts ...grpc.CallOption) (*TransactionListResponse, error)
	UpdateTransaction(ctx context.Context, in *UpdateTransactionRequest, opts ...grpc.CallOption) (*TransactionItem, error)
	DeleteTransaction(ctx context.Context, in *DeleteTransactionRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Budgeting & Envelopes
	GetEnvelope(ctx context.Context, in *GetEnvelopeRequest, opts ...grpc.CallOption) (*EnvelopeItem, error)
	GetEnvelopesByUser(ctx context.Context, in *GetEnvelopesByUserRequest, opts ...grpc.CallOption) (*EnvelopeListResponse, error)
}

type penneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPenneServiceClient(cc grpc.ClientConnInterface) PenneServiceClient {
	return &penneServiceClient{cc}
}

func (c *penneServiceClient) CheckHealth(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PenneService_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *penneServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, PenneService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *penneServiceClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*TransactionItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionItem)
	err := c.cc.Invoke(ctx, PenneService_CreateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *penneServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*TransactionItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionItem)
	err := c.cc.Invoke(ctx, PenneService_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *penneServiceClient) GetTransactionsByUser(ctx context.Context, in *GetTransactionsByUserRequest, opts ...grpc.CallOption) (*TransactionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionListResponse)
	err := c.cc.Invoke(ctx, PenneService_GetTransactionsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *penneServiceClient) UpdateTransaction(ctx context.Context, in *UpdateTransactionRequest, opts ...grpc.CallOption) (*TransactionItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionItem)
	err := c.cc.Invoke(ctx, PenneService_UpdateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *penneServiceClient) DeleteTransaction(ctx context.Context, in *DeleteTransactionRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, PenneService_DeleteTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *penneServiceClient) GetEnvelope(ctx context.Context, in *GetEnvelopeRequest, opts ...grpc.CallOption) (*EnvelopeItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvelopeItem)
	err := c.cc.Invoke(ctx, PenneService_GetEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *penneServiceClient) GetEnvelopesByUser(ctx context.Context, in *GetEnvelopesByUserRequest, opts ...grpc.CallOption) (*EnvelopeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvelopeListResponse)
	err := c.cc.Invoke(ctx, PenneService_GetEnvelopesByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PenneServiceServer is the server API for PenneService service.
// All implementations must embed UnimplementedPenneServiceServer
// for forward compatibility.
//
// Service definition
type PenneServiceServer interface {
	CheckHealth(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// User
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	// Transaction
	CreateTransaction(context.Context, *CreateTransactionRequest) (*TransactionItem, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*TransactionItem, error)
	GetTransactionsByUser(context.Context, *GetTransactionsByUserRequest) (*TransactionListResponse, error)
	UpdateTransaction(context.Context, *UpdateTransactionRequest) (*TransactionItem, error)
	DeleteTransaction(context.Context, *DeleteTransactionRequest) (*DeleteResponse, error)
	// Budgeting & Envelopes
	GetEnvelope(context.Context, *GetEnvelopeRequest) (*EnvelopeItem, error)
	GetEnvelopesByUser(context.Context, *GetEnvelopesByUserRequest) (*EnvelopeListResponse, error)
	mustEmbedUnimplementedPenneServiceServer()
}

// UnimplementedPenneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPenneServiceServer struct{}

func (UnimplementedPenneServiceServer) CheckHealth(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedPenneServiceServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedPenneServiceServer) CreateTransaction(context.Context, *CreateTransactionRequest) (*TransactionItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedPenneServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*TransactionItem, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedPenneServiceServer) GetTransactionsByUser(context.Context, *GetTransactionsByUserRequest) (*TransactionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionsByUser not implemented")
}
func (UnimplementedPenneServiceServer) UpdateTransaction(context.Context, *UpdateTransactionRequest) (*TransactionItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTransaction not implemented")
}
func (UnimplementedPenneServiceServer) DeleteTransaction(context.Context, *DeleteTransactionRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTransaction not implemented")
}
func (UnimplementedPenneServiceServer) GetEnvelope(context.Context, *GetEnvelopeRequest) (*EnvelopeItem, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnvelope not implemented")
}
func (UnimplementedPenneServiceServer) GetEnvelopesByUser(context.Context, *GetEnvelopesByUserRequest) (*EnvelopeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnvelopesByUser not implemented")
}
func (UnimplementedPenneServiceServer) mustEmbedUnimplementedPenneServiceServer() {}
func (UnimplementedPenneServiceServer) testEmbeddedByValue()                      {}

// UnsafePenneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PenneServiceServer will
// result in compilation errors.
type UnsafePenneServiceServer interface {
	mustEmbedUnimplementedPenneServiceServer()
}

func RegisterPenneServiceServer(s grpc.ServiceRegistrar, srv PenneServiceServer) {
	// If the following call panics, it indicates UnimplementedPenneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PenneService_ServiceDesc, srv)
}

func _PenneService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PenneServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PenneService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PenneServiceServer).CheckHealth(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PenneService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PenneServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PenneService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PenneServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PenneService_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PenneServiceServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PenneService_CreateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PenneServiceServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PenneService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PenneServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PenneService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PenneServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PenneService_GetTransactionsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PenneServiceServer).GetTransactionsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PenneService_GetTransactionsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PenneServiceServer).GetTransactionsByUser(ctx, req.(*GetTransactionsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PenneService_UpdateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PenneServiceServer).UpdateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PenneService_UpdateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PenneServiceServer).UpdateTransaction(ctx, req.(*UpdateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PenneService_DeleteTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PenneServiceServer).DeleteTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PenneService_DeleteTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PenneServiceServer).DeleteTransaction(ctx, req.(*DeleteTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PenneService_GetEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PenneServiceServer).GetEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PenneService_GetEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PenneServiceServer).GetEnvelope(ctx, req.(*GetEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PenneService_GetEnvelopesByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvelopesByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PenneServiceServer).GetEnvelopesByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PenneService_GetEnvelopesByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PenneServiceServer).GetEnvelopesByUser(ctx, req.(*GetEnvelopesByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PenneService_ServiceDesc is the grpc.ServiceDesc for PenneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PenneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "penne.v1.PenneService",
	HandlerType: (*PenneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _PenneService_CheckHealth_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _PenneService_GetUser_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _PenneService_CreateTransaction_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _PenneService_GetTransaction_Handler,
		},
		{
			MethodName: "GetTransactionsByUser",
			Handler:    _PenneService_GetTransactionsByUser_Handler,
		},
		{
			MethodName: "UpdateTransaction",
			Handler:    _PenneService_UpdateTransaction_Handler,
		},
		{
			MethodName: "DeleteTransaction",
			Handler:    _PenneService_DeleteTransaction_Handler,
		},
		{
			MethodName: "GetEnvelope",
			Handler:    _PenneService_GetEnvelope_Handler,
		},
		{
			MethodName: "GetEnvelopesByUser",
			Handler:    _PenneService_GetEnvelopesByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pennev1/penne.proto",
}
