// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/pennev1/penne.proto

package pennev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common status
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// User messages
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	MonthlyIncome float64                `protobuf:"fixed64,4,opt,name=monthly_income,json=monthlyIncome,proto3" json:"monthly_income,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{3}
}

func (x *UserResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetMonthlyIncome() float64 {
	if x != nil {
		return x.MonthlyIncome
	}
	return 0
}

// Transaction messages
type TransactionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Remarks       string                 `protobuf:"bytes,6,opt,name=remarks,proto3" json:"remarks,omitempty"`
	EnvelopeId    string                 `protobuf:"bytes,7,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionItem) Reset() {
	*x = TransactionItem{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionItem) ProtoMessage() {}

func (x *TransactionItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionItem.ProtoReflect.Descriptor instead.
func (*TransactionItem) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionItem) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *TransactionItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TransactionItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TransactionItem) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *TransactionItem) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Remarks       string                 `protobuf:"bytes,5,opt,name=remarks,proto3" json:"remarks,omitempty"`
	EnvelopeId    string                 `protobuf:"bytes,6,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTransactionRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTransactionRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateTransactionRequest) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *CreateTransactionRequest) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

type GetTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionUuid string                 `protobuf:"bytes,1,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionRequest) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

type GetTransactionsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByUserRequest) Reset() {
	*x = GetTransactionsByUserRequest{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByUserRequest) ProtoMessage() {}

func (x *GetTransactionsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionsByUserRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetTransactionsByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionsByUserRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type TransactionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionItem     `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionListResponse) Reset() {
	*x = TransactionListResponse{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionListResponse) ProtoMessage() {}

func (x *TransactionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionListResponse.ProtoReflect.Descriptor instead.
func (*TransactionListResponse) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionListResponse) GetTransactions() []*TransactionItem {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *TransactionListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Remarks       string                 `protobuf:"bytes,6,opt,name=remarks,proto3" json:"remarks,omitempty"`
	EnvelopeId    string                 `protobuf:"bytes,7,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTransactionRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateTransactionRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UpdateTransactionRequest) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *UpdateTransactionRequest) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

type DeleteTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionUuid string                 `protobuf:"bytes,1,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTransactionRequest) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Envelope messages
type EnvelopeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	BudgetLimit   float64                `protobuf:"fixed64,4,opt,name=budget_limit,json=budgetLimit,proto3" json:"budget_limit,omitempty"`
	UserUuid      string                 `protobuf:"bytes,5,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeItem) Reset() {
	*x = EnvelopeItem{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeItem) ProtoMessage() {}

func (x *EnvelopeItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeItem.ProtoReflect.Descriptor instead.
func (*EnvelopeItem) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{12}
}

func (x *EnvelopeItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnvelopeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvelopeItem) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *EnvelopeItem) GetBudgetLimit() float64 {
	if x != nil {
		return x.BudgetLimit
	}
	return 0
}

func (x *EnvelopeItem) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type GetEnvelopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvelopeId    string                 `protobuf:"bytes,1,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvelopeRequest) Reset() {
	*x = GetEnvelopeRequest{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvelopeRequest) ProtoMessage() {}

func (x *GetEnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvelopeRequest.ProtoReflect.Descriptor instead.
func (*GetEnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{13}
}

func (x *GetEnvelopeRequest) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

type GetEnvelopesByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvelopesByUserRequest) Reset() {
	*x = GetEnvelopesByUserRequest{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvelopesByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvelopesByUserRequest) ProtoMessage() {}

func (x *GetEnvelopesByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvelopesByUserRequest.ProtoReflect.Descriptor instead.
func (*GetEnvelopesByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{14}
}

func (x *GetEnvelopesByUserRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type EnvelopeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelopes     []*EnvelopeItem        `protobuf:"bytes,1,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeListResponse) Reset() {
	*x = EnvelopeListResponse{}
	mi := &file_proto_pennev1_penne_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeListResponse) ProtoMessage() {}

func (x *EnvelopeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pennev1_penne_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeListResponse.ProtoReflect.Descriptor instead.
func (*EnvelopeListResponse) Descriptor() ([]byte, []int) {
	return file_proto_pennev1_penne_proto_rawDescGZIP(), []int{15}
}

func (x *EnvelopeListResponse) GetEnvelopes() []*EnvelopeItem {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

var File_proto_pennev1_penne_proto protoreflect.FileDescriptor

const file_proto_pennev1_penne_proto_rawDesc = "" +
	"\n" +
	"\x19proto/pennev1/penne.proto\x12\bpenne.v1\"\x14\n" +
	"\x12HealthCheckRequest\"n\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"-\n" +
	"\x0eGetUserRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"s\n" +
	"\fUserResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0emonthly_income\x18\x04 \x01(\x01R\rmonthlyIncome\"\xc1\x01\n" +
	"\x0fTransactionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x18\n" +
	"\aremarks\x18\x06 \x01(\tR\aremarks\x12\x1f\n" +
	"\venvelope_id\x18\a \x01(\tR\n" +
	"envelopeId\"\xba\x01\n" +
	"\x18CreateTransactionRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x18\n" +
	"\aremarks\x18\x05 \x01(\tR\aremarks\x12\x1f\n" +
	"\venvelope_id\x18\x06 \x01(\tR\n" +
	"envelopeId\"B\n" +
	"\x15GetTransactionRequest\x12)\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x0ftransactionUuid\"i\n" +
	"\x1cGetTransactionsByUserRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"y\n" +
	"\x17TransactionListResponse\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.penne.v1.TransactionItemR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xca\x01\n" +
	"\x18UpdateTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x18\n" +
	"\aremarks\x18\x06 \x01(\tR\aremarks\x12\x1f\n" +
	"\venvelope_id\x18\a \x01(\tR\n" +
	"envelopeId\"E\n" +
	"\x18DeleteTransactionRequest\x12)\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x0ftransactionUuid\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8c\x01\n" +
	"\fEnvelopeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12!\n" +
	"\fbudget_limit\x18\x04 \x01(\x01R\vbudgetLimit\x12\x1b\n" +
	"\tuser_uuid\x18\x05 \x01(\tR\buserUuid\"5\n" +
	"\x12GetEnvelopeRequest\x12\x1f\n" +
	"\venvelope_id\x18\x01 \x01(\tR\n" +
	"envelopeId\"8\n" +
	"\x19GetEnvelopesByUserRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"L\n" +
	"\x14EnvelopeListResponse\x124\n" +
	"\tenvelopes\x18\x01 \x03(\v2\x16.penne.v1.EnvelopeItemR\tenvelopes2\xe4\x05\n" +
	"\fPenneService\x12J\n" +
	"\vCheckHealth\x12\x1c.penne.v1.HealthCheckRequest\x1a\x1d.penne.v1.HealthCheckResponse\x12;\n" +
	"\aGetUser\x12\x18.penne.v1.GetUserRequest\x1a\x16.penne.v1.UserResponse\x12R\n" +
	"\x11CreateTransaction\x12\".penne.v1.CreateTransactionRequest\x1a\x19.penne.v1.TransactionItem\x12L\n" +
	"\x0eGetTransaction\x12\x1f.penne.v1.GetTransactionRequest\x1a\x19.penne.v1.TransactionItem\x12b\n" +
	"\x15GetTransactionsByUser\x12&.penne.v1.GetTransactionsByUserRequest\x1a!.penne.v1.TransactionListResponse\x12R\n" +
	"\x11UpdateTransaction\x12\".penne.v1.UpdateTransactionRequest\x1a\x19.penne.v1.TransactionItem\x12Q\n" +
	"\x11DeleteTransaction\x12\".penne.v1.DeleteTransactionRequest\x1a\x18.penne.v1.DeleteResponse\x12C\n" +
	"\vGetEnvelope\x12\x1c.penne.v1.GetEnvelopeRequest\x1a\x16.penne.v1.EnvelopeItem\x12Y\n" +
	"\x12GetEnvelopesByUser\x12#.penne.v1.GetEnvelopesByUserRequest\x1a\x1e.penne.v1.EnvelopeListResponseB>Z<github.com/barathsurya2004/go-code/pkg/proto/pennev1;pennev1b\x06proto3"

var (
	file_proto_pennev1_penne_proto_rawDescOnce sync.Once
	file_proto_pennev1_penne_proto_rawDescData []byte
)

func file_proto_pennev1_penne_proto_rawDescGZIP() []byte {
	file_proto_pennev1_penne_proto_rawDescOnce.Do(func() {
		file_proto_pennev1_penne_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pennev1_penne_proto_rawDesc), len(file_proto_pennev1_penne_proto_rawDesc)))
	})
	return file_proto_pennev1_penne_proto_rawDescData
}

var file_proto_pennev1_penne_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_pennev1_penne_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),           // 0: penne.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),          // 1: penne.v1.HealthCheckResponse
	(*GetUserRequest)(nil),               // 2: penne.v1.GetUserRequest
	(*UserResponse)(nil),                 // 3: penne.v1.UserResponse
	(*TransactionItem)(nil),              // 4: penne.v1.TransactionItem
	(*CreateTransactionRequest)(nil),     // 5: penne.v1.CreateTransactionRequest
	(*GetTransactionRequest)(nil),        // 6: penne.v1.GetTransactionRequest
	(*GetTransactionsByUserRequest)(nil), // 7: penne.v1.GetTransactionsByUserRequest
	(*TransactionListResponse)(nil),      // 8: penne.v1.TransactionListResponse
	(*UpdateTransactionRequest)(nil),     // 9: penne.v1.UpdateTransactionRequest
	(*DeleteTransactionRequest)(nil),     // 10: penne.v1.DeleteTransactionRequest
	(*DeleteResponse)(nil),               // 11: penne.v1.DeleteResponse
	(*EnvelopeItem)(nil),                 // 12: penne.v1.EnvelopeItem
	(*GetEnvelopeRequest)(nil),           // 13: penne.v1.GetEnvelopeRequest
	(*GetEnvelopesByUserRequest)(nil),    // 14: penne.v1.GetEnvelopesByUserRequest
	(*EnvelopeListResponse)(nil),         // 15: penne.v1.EnvelopeListResponse
}
var file_proto_pennev1_penne_proto_depIdxs = []int32{
	4,  // 0: penne.v1.TransactionListResponse.transactions:type_name -> penne.v1.TransactionItem
	12, // 1: penne.v1.EnvelopeListResponse.envelopes:type_name -> penne.v1.EnvelopeItem
	0,  // 2: penne.v1.PenneService.CheckHealth:input_type -> penne.v1.HealthCheckRequest
	2,  // 3: penne.v1.PenneService.GetUser:input_type -> penne.v1.GetUserRequest
	5,  // 4: penne.v1.PenneService.CreateTransaction:input_type -> penne.v1.CreateTransactionRequest
	6,  // 5: penne.v1.PenneService.GetTransaction:input_type -> penne.v1.GetTransactionRequest
	7,  // 6: penne.v1.PenneService.GetTransactionsByUser:input_type -> penne.v1.GetTransactionsByUserRequest
	9,  // 7: penne.v1.PenneService.UpdateTransaction:input_type -> penne.v1.UpdateTransactionRequest
	10, // 8: penne.v1.PenneService.DeleteTransaction:input_type -> penne.v1.DeleteTransactionRequest
	13, // 9: penne.v1.PenneService.GetEnvelope:input_type -> penne.v1.GetEnvelopeRequest
	14, // 10: penne.v1.PenneService.GetEnvelopesByUser:input_type -> penne.v1.GetEnvelopesByUserRequest
	1,  // 11: penne.v1.PenneService.CheckHealth:output_type -> penne.v1.HealthCheckResponse
	3,  // 12: penne.v1.PenneService.GetUser:output_type -> penne.v1.UserResponse
	4,  // 13: penne.v1.PenneService.CreateTransaction:output_type -> penne.v1.TransactionItem
	4,  // 14: penne.v1.PenneService.GetTransaction:output_type -> penne.v1.TransactionItem
	8,  // 15: penne.v1.PenneService.GetTransactionsByUser:output_type -> penne.v1.TransactionListResponse
	4,  // 16: penne.v1.PenneService.UpdateTransaction:output_type -> penne.v1.TransactionItem
	11, // 17: penne.v1.PenneService.DeleteTransaction:output_type -> penne.v1.DeleteResponse
	12, // 18: penne.v1.PenneService.GetEnvelope:output_type -> penne.v1.EnvelopeItem
	15, // 19: penne.v1.PenneService.GetEnvelopesByUser:output_type -> penne.v1.EnvelopeListResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_pennev1_penne_proto_init() }
func file_proto_pennev1_penne_proto_init() {
	if File_proto_pennev1_penne_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pennev1_penne_proto_rawDesc), len(file_proto_pennev1_penne_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pennev1_penne_proto_goTypes,
		DependencyIndexes: file_proto_pennev1_penne_proto_depIdxs,
		MessageInfos:      file_proto_pennev1_penne_proto_msgTypes,
	}.Build()
	File_proto_pennev1_penne_proto = out.File
	file_proto_pennev1_penne_proto_goTypes = nil
	file_proto_pennev1_penne_proto_depIdxs = nil
}
